routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {return redirect('home');})->middleware('auth');
Route::get('/welcome', function () {
    return view('welcome');
})->name('welcome');

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth', 'admin'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');
});

Route::group(['middleware' => 'auth', 'admin'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

	Route::resource('product', 'ProductController');
    Route::post('inventory-upload', 'ProductController@inventoryUpload')->name('product.inventory-upload');

	Route::resource('category', 'CategoryController');
	Route::resource('transaction', 'TransactionController');
    Route::get('transaction/{id}/data', 'TransactionController@listData')->name('transaction.data');
    Route::post('transaction/addItem', 'TransactionController@addItem')->name('transaction.addItem');
    Route::get('transaction/loadform/{discount}/{total}/{received}', 'TransactionController@loadForm');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['productCode', 'title', 'description', 'brand', 'partNumber', 'model', 'categoryId'];
    public $timestamps = true;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Category;
use App\Inventory;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::select('products.*','category.title as categoryTitle', 'inventory.price', 'inventory.cost', 'inventory.price', 'inventory.quantity')->leftJoin('category', 'products.categoryId', '=', 'category.id')->leftJoin('inventory', 'products.id', '=', 'inventory.id')->get();
        $categories = Category::all();

        return view('products.index', ['products' => $products, 'categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->file('fileUploadProduct'))
        {
            $dataFile = $request->file('fileUploadProduct');
            $dataFile->move('uploads',$dataFile->getClientOriginalName());
            
            $newPath = public_path('uploads/'.$dataFile->getClientOriginalName());

            $productsArray = $this->csvToArray($newPath);

            for ($i = 0; $i < count($productsArray); $i ++)
            {
                $category = Category::where('id', $productsArray[$i]['category'])->first();

                if ( !is_null($category) ) 
                {
                    $isAvailable = Product::where( 'productCode', $productsArray[$i]['productcode'] )->first();
    
                    if ( is_null($isAvailable) )
                    {
                        $product = Product::create([
                            'productCode' => $productsArray[$i]['productcode'],
                            'title' => $productsArray[$i]['title'],
                            'description' => $productsArray[$i]['description'],
                            'brand' => $productsArray[$i]['brand'],
                            'partNumber' => intval( ($productsArray[$i]['partnumber'] != "") ? $productsArray[$i]['partnumber'] : null ),
                            'model' => $productsArray[$i]['model'],
                            'categoryId' => intval( ($productsArray[$i]['category'] != "") ? $productsArray[$i]['category'] : null ),
                        ]);
            
                        $inventory = Inventory::create([
                            'productId' => $product->id,
                            'quantity' => 0,
                            'cost' => 0,
                            'price' => 0,
                        ]);
                    }
                    else 
                    {
                        $isAvailable->productCode = $productsArray[$i]['productcode'];
                        $isAvailable->title = $productsArray[$i]['title'];
                        $isAvailable->description = $productsArray[$i]['description'];
                        $isAvailable->brand = $productsArray[$i]['brand'];
                        $isAvailable->partNumber = intval( ($productsArray[$i]['partnumber'] != "") ? $productsArray[$i]['partnumber'] : null );
                        $isAvailable->model = $productsArray[$i]['model'];
                        $isAvailable->categoryId = intval( ($productsArray[$i]['category'] != "") ? $productsArray[$i]['category'] : null );

                        $isAvailable->save();
                    }
                }
                else 
                {

                }
            }

            unlink($newPath);
            return response()->json(true);
        }
        else 
        {
            if ( $request->productId !== null ) if ($this->update($request) ) return redirect()->back();

            $product = Product::create([
                'productCode' => $request->productCode,
                'title' => $request->title,
                'description' => $request->description,
                'brand' => $request->brand,
                'partNumber' => $request->partNumber,
                'model' => $request->model,
                'categoryId' => $request->category,
            ]);

            $inventory = Inventory::create([
                'productId' => $product->id,
                'quantity' => 0,
                'cost' => 0,
                'price' => 0,
            ]);
            
            if ( $product && $inventory) return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        if (\Illuminate\Support\Facades\Auth::user()->level != 1) return redirect('/pos');
        $product = Product::find($request->productId);

        $product->productCode = $request->productCode;
        $product->title = $request->title;
        $product->description = $request->description;
        $product->brand = $request->brand;
        $product->partNumber = $request->partNumber;
        $product->model = $request->model;
        $product->categoryId = $request->category;

        return $product->save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function inventoryUpload( Request $request )
    {
        if (\Illuminate\Support\Facades\Auth::user()->level != 1) return redirect('/pos');
        if ($request->file('fileUpload')) 
        {
            $dataFile = $request->file('fileUpload');
            $dataFile->move('uploads',$dataFile->getClientOriginalName());
            
            $newPath = public_path('uploads/'.$dataFile->getClientOriginalName());

            $productsArray = $this->csvToArray($newPath);

            for ($i = 0; $i < count($productsArray); $i ++)
            {
                $productId = Product::where( 'productCode', $productsArray[$i]['productcode'] )->first();

                if ( !is_null($productId) ) {
                    $inventory = Inventory::where('id', $productId['id'])->first();
                
                    if (!is_null($inventory) ) {
                        $inventory['quantity'] = floatval($productsArray[$i]['quantity']);
        
                        $inventory->save();
                    }
                }
            }

            unlink($newPath);
        }
        return response()->json(true);
    }

    function csvToArray($filename = '', $delimiter = ',')
    {
        if (!file_exists($filename) || !is_readable($filename)) return false;

        $header = null;
        $data = array();
        if (($handle = fopen($filename, 'r')) !== false)
        {
            while (($row = fgetcsv($handle, 1000, $delimiter)) !== false)
            {
                if (!$header)
                    $header = $row;
                else
                    $data[] = array_combine($header, $row);
            }
            fclose($handle);
        }

        return $data;
    }
}

resources/views/products/index.blade.php
@extends('layouts.app', ['activePage' => 'product-management', 'titlePage' =>'Product Managenent'])

@section('content')
  <div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header card-header-danger color-theme">
              <h4 class="card-title ">Products</h4>
              <p class="card-category"> Here you can manage all product details and inventory</p>
            </div>
            
            <div class="card-body">
              <div class="row">
                <div class="col-12 text-right">
                  <a href="#" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#productAddModal" onclick="clearFields()">Add product</a>
                  <a href="#" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#uploadInventory">Upload Inventory</a>
                  {{-- <div class="file btn btn-success">
                    Upload Inventory
                    <input type="file" name="file" style="position: absolute;font-size: 50px;opacity: 0;right: 0;top: 0;" accept=".xls,.xlsx,.csv"/>
                  </div> --}}
                </div>
              </div>
              <div class="table-responsive">
                <table class="table" id="dataTable">
                  <thead class=" text-primary">
                    <tr>
                      <th>Product Code</th>
                      <th>Title</th>
                      <th>Description</th>
                      <th>Brand</th>
                      <th>Category</th>
                      <th>Cost</th>
                      <th>Price</th>
                      <th>Inventory Available</th>
                      @if ( auth()->user() )
                        <th class="text-right">
                          Actions
                        </th>
                      @endif
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ( $products as $product )
                        <tr>
                          <td>{{ $product->productCode }}</td>
                          <td>
                            {{ $product->title }}
                            <input type="text" hidden id="title{{ $product->productCode }}" value="{{ $product->title }}">
                          </td>
                          <td>
                            {{ $product->description }}
                            <input type="text" hidden id="description{{ $product->productCode }}" value="{{ $product->description }}">
                          </td>
                          <td>
                            {{ $product->brand }}
                            <input type="text" hidden id="brand{{ $product->productCode }}" value="{{ $product->brand }}">
                          </td>
                          <td>
                            {{ $product->categoryTitle }}
                            <input type="text" hidden id="category{{ $product->productCode }}" value="{{ $product->categoryId }}">
                          </td>
                          <td>{{ ($product->cost > 0) ? $product->cost : 0.00 }}</td>
                          <td>{{ ($product->price > 0) ? $product->price : 0.00 }}</td>
                          <td>{{ ($product->quantity > 0) ? $product->quantity : 0.00 }}</td>
                          @if ( auth()->user() )
                            <td class="td-actions text-right">
                              <button type="button" rel="tooltip" title="" class="btn btn-primary btn-link btn-sm" data-original-title="Edit" data-toggle="modal" data-target="#productAddModal" onclick="loadModal('{{$product->productCode}}', '{{$product->id}}')">
                                <i class="material-icons">edit</i>
                                <div class="ripple-container"></div>
                              </button>
                            </td>
                          @endif
                        </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
    </div>
  </div>
  <script>

    $.ajaxSetup({
      headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      }
    });

    function loadModal( productCode, productId )
    {
      $('#modal-productCode').val( productCode );
      $('#modal-title').val( $('#title'+productCode).val() );
      $('#modal-description').val( $('#description'+productCode).val() );
      $('#modal-brand').val( $('#brand'+productCode).val() );
      $('#modal-category').val( $('#category'+productCode).val() );
      $('#modal-productId').val( productId );
    }

    function clearFields()
    {
      $('#modal-productCode').val("");
      $('#modal-title').val("");
      $('#modal-description').val("");
      $('#modal-brand').val("");
      $('#modal-productId').val("");
    }

    function inventoryUpload()
    {
      $('#loader').removeAttr('hidden');
      $("#uploadButton").attr("hidden",true);

      let formData = new FormData($('#upload-file-form')[0]);

      $.ajax({
        type:'POST',
        url: `{{ route("product.inventory-upload") }}`,
        data: formData,
        contentType: false,
        processData: false,
        success: (response) => 
        {
          $("#loader").attr("hidden",true);
          $('#uploadButton').removeAttr('hidden');

          if (response) $('#uploadInventory').modal('hide');
          location.reload();
        },
        error: function(response)
        {
          console.log(response);
        }
      });
    }

    function productUpload()
    {
      $('#loader').removeAttr('hidden');

      let formData = new FormData($('#upload-product-form')[0]);

      $.ajax({
        type:'POST',
        url: `{{ route("product.store") }}`,
        data: formData,
        contentType: false,
        processData: false,
        success: (response) => 
        {
          $("#loader").attr("hidden",true);

          if (response) $('#productAddModal').modal('hide');
          location.reload();
        },
        error: function(response)
        {
          console.log(response);
        }
      });
    }
  </script>
@endsection